10015	WARN	(Incomplete or No Cache-control Header)
10027	WARN	(Information Disclosure - Suspicious Comments)
10096	WARN	(Timestamp Disclosure)
10109	IGNORE	(Modern Web Application)
90022	WARN	(Application Error Disclosure)
10038	WARN	(Content Security Policy Header Not Set)
10035	WARN	(Strict-Transport-Security Header Not Set)
10036	WARN	(Server Leaks Version Information)
10021	WARN	(X-Content-Type-Options Header Missing)
10020	WARN	(X-Frame-Options Header Not Set)
